### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by SteveALee** [Azure/aci-issues#1]
When playing with ACI last week I had an number of issues. and thought I'd list them here in case they are of use. They are not all problems with ACI itself.

For fun I decided to follow [an example](https://cmatskas.com/getting-started-with-azure-container-instances/) of building a dot net app and deploying it to ACS but rather than using OS X like the original I used WSL and Docker for Windows, see [this issue](https://github.com/docker/for-win/issues/958) for details
 
* Docker could not connect to the ACR - turned out I needed to set it to use 8.8.8.8 DNS server. Seems to be a known problem. Wasted a lot of time playing with UDP on my home router firewall ;)

* I specified a Basic container with the CLI but it's listed as 'Classic' in the portal. Confusingly there is another Basic type listed in the portal when you created there

* When the runtime was broken -eg non existent entry point, ACIs stayed in the 'Creating' state forever according to the CLI. I can recall the details but I found I had zombie ACIs I could see in portal but not delete from the ACI.

* There is no way to delete an ACI in the portal

* The create process in the CLI is async so you need to keep running a command to see if it is started. Can you make the create command sync by running a throbber till it's started, like some of the other CLI commands? I know this will make it seem longer to start and depends of container contents but it would be more usefull although not so nice a selling point.

I hope that is useful

**Comment by seanmck** [comment]
Thanks for the feedback, @SteveALee. 

In your 2nd bullet, are you referring to storage containers? There is no 'classic' deployment model for ACI itself.

For the 3rd item, I recently wrote some troubleshooting guidance: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-troubleshooting

For the 4th item: this is in the process of rolling out. You can see the latest UX at aka.ms/acibrowse

For the final item, you can get a synchronous model if you deploy with an ARM template. Otherwise, it is async like most other modules in the az CLI.

Since this issue covers multiple topics, I'm going to close it. If you find any of these response insufficient, please refile as new, individual issues. That will make them easier to discuss and track.
